spring:
  application:
    name: ms-order
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    properties:
      hibernate.default_schema: ordering
    hibernate:
      ddl-auto: none
  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${PROVIDER_ISSUER_URI}

server:
  port: ${APP_PORT}

inventory:
  base-url: ${INVENTORY_BASE_URL}
  sell-endpoint: ${INVENTORY_SELL_ENDPOINT}

order:
  decrease-stock-enabled: ${ORDER_DECREASE_STOCK_ENABLE}

springdoc:
  swagger-ui:
    path: /index.html
    enabled: false
  api-docs:
    enabled: false
    path: /v3/api-docs