apiVersion: v1
kind: Service
metadata:
  name: ms-order-service
spec:
  selector:
    app: ms-order
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080
      nodePort: 30003
  type: NodePort
